F_exp_date/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from product.views import show_main_page
from F_exp_date.settings import DEBUG



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', show_main_page, name='main_page'),
    path('', include('product.urls', namespace='product')),
    path('', include('market_dashbord.urls', namespace='market_dashbord')),
    path('', include('users.urls', namespace='users'))

]
if DEBUG==True:
    # включаем возможность обработки картинок
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market_dashbord/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from market_dashbord.views import *

app_name = 'market_dashbord'

urlpatterns = [
    path('show_all_markets', show_all_markets, name='show_all_markets'),
    path('show_my_market', show_my_market, name='show_my_market'),
    path('market_detail/<int:pk>/', show_market, name='market_detail'),
    path('new-market', create_new_market, name='create_new_market'),
    path('show_contacts', show_contacts, name='show_contacts'),
    path('show_6_day_food', show_6_day_food, name='show_6_day_food'),
    path('show_30_day_food', show_30_day_food, name='show_30_day_food'),
    path('create_food_record', create_food_record, name='create_food_record'),
    path('write_off_product/<int:pk>/', write_off_product, name='write_off_product'),
    path('show_write_off', show_write_off, name='show_write_off'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),

    path('edit/', views.edit, name='edit'),

    # path('employee/register/', views.employee_registration, name='employee-registration'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>{{ title }}</title>
    {% endblock %}

    <!-- Favicon -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'images/favicon.png' %}" />
    
    {# Load the tag library #}
    {% load bootstrap5 %}
    
    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    
    {# Display django.contrib.messages as Bootstrap alerts #}
    {% bootstrap_messages %}


    {% block css %}
    <!-- CUSTOM CSS -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock %}
    
    {% block js %}
    
    {% endblock %}
</head>
<body class="body-wrapper" data-spy="scroll" data-target=".privacy-nav">
    {% block body %}

    {% block header %}
        {% include 'base/header.html' %}
    {% endblock header %}

    {% block menu %}
        {% include 'base/main-menu.html' %}
    {% endblock menu %}
        <br>
            {% block content %}
            {% endblock content %}

            {% include 'base/footer.html' %}
            {% include 'base/scripts.html' %}
    {% endblock body %}
</body>
</html>

templates/base/footer.html
<!-- Футер сайта -->

templates/base/header.html
<!-- Заголовки, иконки, логотипы -->

templates/base/main-menu.html
<!-- Главная-> Инструкция к приложению -> Красивый Landing Page
  
если залогиниться:
    Добавить товар в базу данных
    Просмотр товара с подходящими сроками годности(6 дней)
    Просмотр товара с подходящими сроками годности(30 дней)

если Менеджер магазина:
    может списывать товар
    Личный кабинет(Управление):
        Доступ для сотрудников магазина
        выгрузки отчетов

Регистрация

Войти -->
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 sticky-top">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main_page' %}">Анти-Просрок</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNavDropdown"
      aria-controls="navbarNavDropdown"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ms-auto">
        <li>
          <a
            class="nav-link mx-2"
            href="{% url 'main_page' %}"
          >
            Начальная
          </a>
        </li>

        {% if user.is_authenticated %}
        <!-- если залогиниться:
        Добавить товар в базу данных
        Просмотр товара с подходящими сроками годности(6 дней)
        Просмотр товара с подходящими сроками годности(30 дней) -->
        <li>
          <a class="nav-link mx-2" href="{% url 'users:edit' %}">
            Профиль: {{ user.username|default:'Пользователь' }}
          </a>
        </li>
        <li class="nav-item">
          <a
            class="nav-link mx-2"
            href="{% url 'market_dashbord:create_food_record' %}"
            >Добавить продукты в магазин</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'market_dashbord:show_6_day_food' %}">Товары с ИСГ <= 6 дней</a>
        </li>
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'market_dashbord:show_30_day_food' %}">Товары с ИСГ <= 30 дней</a>
        </li>

        {% else %}
        <li class="nav-item">
          <a class="nav-link mx-2" href="{% url 'users:register' %}"
            >Зарегистрироваться</a
          >
        </li>

        {% endif %}

        <li>
          {% if user.is_authenticated %}
          <a class="nav-link mx-2" href="{% url 'users:logout' %}">Выйти</a>
          {% else %}
          <a class="nav-link mx-2" href="{% url 'users:login' %}">Войти</a>
          {% endif %}
        </li>
        <li>
          <a
            class="nav-link mx-2"
            href="{% url 'market_dashbord:show_contacts' %}"
          >
            Контакты
          </a>
        </li>
        <li class="nav-item dropdown">
          <a
            class="nav-link mx-2 dropdown-toggle"
            href="#"
            id="navbarDropdownMenuLink"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            Дополнительно
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li>
              <a class="dropdown-item" href="{% url 'users:register' %}"
                >Зарегистрироваться</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'market_dashbord:show_all_markets' %}"
                >Список Магазинов</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'market_dashbord:show_my_market' %}"
                >Выбрать свой магазин</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'market_dashbord:create_new_market' %}"
                >Добавить свой магазин</a
              >
            </li>
            <li>
              <a
                class="dropdown-item"
                href="{% url 'market_dashbord:show_write_off' %}"
                >Списанные продукты</a
              >
            </li>
            <li>
              <a class="dropdown-item" href="{% url 'admin:login' %}"
                >ADMIN panel</a
              >
            </li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/base/pagination.html
			<div class="col-12">
				<!-- Pagination -->
				<nav class="pagination-nav">
				  <ul class="pagination">
				    <li class="page-item active"><a class="page-link" href="#">1</a></li>
				    <li class="page-item"><a class="page-link" href="#">2</a></li>
				    <li class="page-item"><a class="page-link" href="#">3</a></li>
				    <li class="page-item">
				      <a class="page-link" href="#" aria-label="Next">
				        <span aria-hidden="true"><i class="ti-angle-right"></i></span>
				        <span class="sr-only">Next</span>
				      </a>
				    </li>
				  </ul>
				</nav>
			</div>

templates/base/scripts.html
<!-- добавлаяем скипты -->
{% load static %}
  <!-- JAVASCRIPTS -->
  <!-- <script src="{% static 'jquery/jquery.min.js' %}"></script> -->
  <!-- <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script> -->
  <!-- <script src="{% static 'plugins/slick/slick.min.js' %}"></script>
  <script src="{% static 'plugins/fancybox/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'plugins/syotimer/jquery.syotimer.min.js' %}"></script>
  <script src="{% static 'plugins/aos/aos.js' %}"></script> -->

templates/base/sign-in.html
<!-- 
THEME: Small Apps | Bootstrap App Landing Template
VERSION: 1.0.0
AUTHOR: Themefisher

HOMEPAGE: https://themefisher.com/products/small-apps-free-app-landing-page-template/
DEMO: https://demo.themefisher.com/small-apps/
GITHUB: https://github.com/themefisher/Small-Apps-Bootstrap-App-Landing-Template

Get HUGO Version : https://themefisher.com/products/small-apps-hugo-app-landing-theme/

WEBSITE: https://themefisher.com
TWITTER: https://twitter.com/themefisher
FACEBOOK: https://www.facebook.com/themefisher
-->

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Small Apps | Bootstrap App Landing Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Bootstrap App Landing Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Small Apps Template v1.0">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="images/favicon.png" />
  
  <!-- PLUGINS CSS STYLE -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <link rel="stylesheet" href="plugins/slick/slick-theme.css">
  <link rel="stylesheet" href="plugins/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="plugins/aos/aos.css">

  <!-- CUSTOM CSS -->
  <link href="css/style.css" rel="stylesheet">

</head>

<body class="body-wrapper" data-spy="scroll" data-target=".privacy-nav">


<section class="user-login section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="block">
					<!-- Image -->
					<div class="image align-self-center"><img class="img-fluid" src="images/Login/front-desk-sign-in.jpg"
							alt="desk-image"></div>
					<!-- Content -->
					<div class="content text-center">
						<div class="logo">
							<a href="index.html"><img src="images/logo.png" alt=""></a>
						</div>
						<div class="title-text">
							<h3>Sign in to To Your Account</h3>
						</div>
						<form action="#">
							<!-- Username -->
							<input class="form-control main" type="text" placeholder="Username" required>
							<!-- Password -->
							<input class="form-control main" type="password" placeholder="Password" required>
							<!-- Submit Button -->
							<button class="btn btn-main-sm">sign in</button>
						</form>
						<div class="new-acount">
							<a href="contact.html">Forget your password?</a>
							<p>Don't Have an account? <a href="sign-up.html"> SIGN UP</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>


  <!-- To Top -->
  <div class="scroll-top-to">
    <i class="ti-angle-up"></i>
  </div>
  
  <!-- JAVASCRIPTS -->
  <script src="plugins/jquery/jquery.min.js"></script>
  <script src="plugins/bootstrap/bootstrap.min.js"></script>
  <script src="plugins/slick/slick.min.js"></script>
  <script src="plugins/fancybox/jquery.fancybox.min.js"></script>
  <script src="plugins/syotimer/jquery.syotimer.min.js"></script>
  <script src="plugins/aos/aos.js"></script>
  <!-- google map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgeuuDfRlweIs7D6uo4wdIHVvJ0LonQ6g"></script>
  <script src="plugins/google-map/gmap.js"></script>
  
  <script src="js/script.js"></script>
</body>

</html>

templates/base/sign-up.html
<!-- 
THEME: Small Apps | Bootstrap App Landing Template
VERSION: 1.0.0
AUTHOR: Themefisher

HOMEPAGE: https://themefisher.com/products/small-apps-free-app-landing-page-template/
DEMO: https://demo.themefisher.com/small-apps/
GITHUB: https://github.com/themefisher/Small-Apps-Bootstrap-App-Landing-Template

Get HUGO Version : https://themefisher.com/products/small-apps-hugo-app-landing-theme/

WEBSITE: https://themefisher.com
TWITTER: https://twitter.com/themefisher
FACEBOOK: https://www.facebook.com/themefisher
-->

<!DOCTYPE html>
<html lang="en">
<head>

  <!-- Basic Page Needs
  ================================================== -->
  <meta charset="utf-8">
  <title>Small Apps | Bootstrap App Landing Template</title>

  <!-- Mobile Specific Metas
  ================================================== -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="Bootstrap App Landing Template">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=5.0">
  <meta name="author" content="Themefisher">
  <meta name="generator" content="Themefisher Small Apps Template v1.0">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/x-icon" href="images/favicon.png" />
  
  <!-- PLUGINS CSS STYLE -->
  <link rel="stylesheet" href="plugins/bootstrap/bootstrap.min.css">
  <link rel="stylesheet" href="plugins/themify-icons/themify-icons.css">
  <link rel="stylesheet" href="plugins/slick/slick.css">
  <link rel="stylesheet" href="plugins/slick/slick-theme.css">
  <link rel="stylesheet" href="plugins/fancybox/jquery.fancybox.min.css">
  <link rel="stylesheet" href="plugins/aos/aos.css">

  <!-- CUSTOM CSS -->
  <link href="css/style.css" rel="stylesheet">

</head>

<body class="body-wrapper" data-spy="scroll" data-target=".privacy-nav">

<!--=============================
=            Sign Up            =
==============================-->

<section class="user-login section">
	<div class="container">
		<div class="row">
			<div class="col-12">
				<div class="block">
					<!-- Image -->
					<div class="image align-self-center"><img class="img-fluid" src="images/Login/sign-up.jpg" alt="desk-image">
					</div>
					<!-- Content -->
					<div class="content text-center">
						<div class="logo">
							<a href="index.html"><img src="images/logo.png" alt=""></a>
						</div>
						<div class="title-text">
							<h3>Sign Up for New Account</h3>
						</div>
						<form action="#">
							<!-- Username -->
							<input class="form-control main" type="text" placeholder="Your Name" required>
							<!-- Email -->
							<input class="form-control main" type="email" placeholder="Email Address" required>
							<!-- Password -->
							<input class="form-control main" type="password" placeholder="Password" required>
							<!-- Submit Button -->
							<button class="btn btn-main-md">sign up</button>
						</form>
						<div class="new-acount">
							<p>By clicking “Sign Up” I agree to <a href="privacy-policy.html">Terms of Conditions.</a></p>
							<p>Anready have an account? <a href="sign-in.html">SIGN IN</a></p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>

<!--====  End of Sign Up  ====-->


  <!-- To Top -->
  <div class="scroll-top-to">
    <i class="ti-angle-up"></i>
  </div>
  
  <!-- JAVASCRIPTS -->
  <script src="plugins/jquery/jquery.min.js"></script>
  <script src="plugins/bootstrap/bootstrap.min.js"></script>
  <script src="plugins/slick/slick.min.js"></script>
  <script src="plugins/fancybox/jquery.fancybox.min.js"></script>
  <script src="plugins/syotimer/jquery.syotimer.min.js"></script>
  <script src="plugins/aos/aos.js"></script>
  <!-- google map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAgeuuDfRlweIs7D6uo4wdIHVvJ0LonQ6g"></script>
  <script src="plugins/google-map/gmap.js"></script>
  
  <script src="js/script.js"></script>
</body>

</html>