F_exp_date/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from product.views import show_main_page
from F_exp_date.settings import DEBUG



urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', show_main_page, name='main_page'),
    path('', include('product.urls', namespace='product')),
    path('', include('market_dashbord.urls', namespace='market_dashbord')),
    path('', include('users.urls', namespace='users'))

]
if DEBUG==True:
    # включаем возможность обработки картинок
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market_dashbord/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from market_dashbord.views import *

app_name = 'market_dashbord'

urlpatterns = [
    path('show_all_markets', show_all_markets, name='show_all_markets'),
    path('show_my_market', show_my_market, name='show_my_market'),
    path('market_detail/<int:pk>/', show_market, name='market_detail'),
    path('new-market', create_new_market, name='create_new_market'),
    path('show_contacts', show_contacts, name='show_contacts'),
    path('show_6_day_food', show_6_day_food, name='show_6_day_food'),
    path('show_30_day_food', show_30_day_food, name='show_30_day_food'),
    path('create_food_record', create_food_record, name='create_food_record'),
    path('write_off_product/<int:pk>/', write_off_product, name='write_off_product'),
    path('show_write_off', show_write_off, name='show_write_off'),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from users import views


app_name = 'users'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),

    path('edit/', views.edit, name='edit'),

    # path('employee/register/', views.employee_registration, name='employee-registration'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/contact.html
{% extends "base\base.html" %}

{% load static %}

{% block title %}
    <title>Контакты</title>
{% endblock %}

{% block content %}

<section class="section page-title">
	<div class="container">
		<div class="row">
			<div class="col-sm-8 m-auto">
				<!-- Page Title -->
				<h1>Продукты с подходящим сроком годности</h1>
				<!-- Page Description -->
                <p>Программный код приложения разрабатываеться с целью повысить качество обслуживания в сетевых магазинах, как ежедневный инструмент работы со сроками годности</p>
                <p>Авторские права и разработчик: Бодров А.В.</p>
                <p>Email : <E-mail>alexvbodrov@mail.ru</E-mail></p>
                
			</div>
		</div>
	</div>
</section>

{% endblock %}

templates/create_food_record.html
{% extends "base\base.html" %} {% load static %} {% block content %}
<div align="center">
  <h2>Добавить товар в базу данных</h2>
  <br />
  <hr />
  <div class="container col-4">
    <!-- Добавить виджет для выбора даты -->
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Сохранить</button>
    </form>
  </div>
</div>
{% endblock content %}

templates/index.html
{% extends "base\base.html" %}
{% load static %}
{%  load %}
{% block content %}
    <h1 align="center">Продукты с подходящим сроком годности</h1>
    <div align="center">
        <h4> Сегодня: {{ date|date:"l d M Y" }}</h4>
        <br><HR>
    
            <h2>Здесь будет Лендинг Продукта</h2>
{% endblock content %}

templates/market_detail.html
{% extends "base\base.html" %}
{% load static %}

{% block content %}
    <h1 align="center">Продукты с подходящим сроком годности</h1>
    <div align="center">
        <h4> Сегодня: {{ date|date:"l d M Y" }}</h4>
        <br><HR>
    
    {% for product in  show_all_products%}
    <li>{{ product.product_name }}</li>
    <li><img src="{{ product.img.url }}" width="200", height="200"></li>

    <li>{{ product.barcode }}</li>
    <li>{{ product.write_off }}</li>
    <li>{{ product.number_of_market }}</li>
    <br>
    <HR>
    {% endfor %}
    </div>
{% endblock content %}

templates/new-market.html
{% extends "base\base.html" %}
{% load static %}

{% block content %}
    <h1 align="center">Продукты с подходящим сроком годности</h1>
    <div align="center">
        <br><HR>
        <h2> Создать магазин</h2>
        
    
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Save</button>
            </form>
    </div>
{% endblock content %}

templates/show_30_day_best_before.html
{% extends "base\base.html" %} {% load static %} {% block content %}
<h1 align="center">Продукты с подходящим сроком годности</h1>
<div align="center">
  <h4>Сегодня: {{ date|date:"l d M Y" }}</h4>
  <br />
  <hr />
  <br />
  {% for product in all_items %}

  <div
    class="card rounded border border-5 {% if product.is_expired %}border-danger {% else %} border-success {% endif %}"
    style="max-width: 35rem"
  >
    <img src="{{ product.img.url }}" class="card-img-top" alt="..." />
    <div class="card-body">
      <h5 class="card-title">Название: {{ product.product_name }}</h5>
      <!-- <p class="card-text">Небольшой пример текста, который должен основываться на названии карты и составлять основную часть содержимого карты.</p> -->
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Годен до: {{ product.date_best_before }}</li>
      <li class="list-group-item">ШК: {{ product.barcode }}</li>
    </ul>
    {% if product.is_expired %}
    <div class="card-body">
      <p class="list-group-item border-danger" style="max-width: 50%">Просроченый</p><br>
      <a
        href="{% url 'market_dashbord:write_off_product' product.pk %}"
        class="btn btn-success"
        >Списать</a
      >
    </div>
    {% endif %}
  </div>

  <br />
  <hr />
  <br />

  {% endfor %}
</div>
{% endblock content %}

templates/show_6_day_best_before.html
{% extends "base\base.html" %}
{% load static %}

{% block content %}
    <h1 align="center">Продукты с подходящим сроком годности</h1>
    <div align="center">
        <h4> Сегодня: {{ date|date:"l d M Y" }}</h4>
        <br><HR>
    
    {% for product in  all_items %}
    <li>{{ product.product_name }}</li>
    <li><img src="{{ product.img.url }}" width="200", height="200"></li>
    <li>{{ product.date_best_before }}</li>
    <li>{{ product.barcode }}</li>
    <li>{{ product.write_off }}</li>
    <li>{{ product.number_of_market }}</li>
    <br>
    <HR>
    {% endfor %}
    </div>
{% endblock content %}

templates/show_all_markets.html
{% extends "base\base.html" %} {% load static %} {% block content %}
<h1 align="center">Продукты с подходящим сроком годности</h1>
<div align="center">
  <h4>Сегодня: {{ date|date:"l d M Y" }}</h4>
  <br />
  <hr />
  <br />
  <div class="container col-4">
    <form class="d-flex">
      <input
        class="form-control me-2"
        type="search"
        placeholder="Поиск"
        aria-label="Поиск"
      />
      <button class="btn btn-outline-success" type="submit">Поиск</button>
    </form>
  </div>
  <br />
  <hr />
  {% for market in all_markets %}
  <a href="{% url 'market_dashbord:market_detail' market.number_market %}">
    <li>{{ market.number_market }}</li>
  </a>
  <li>{{ market.adress_market }}</li>
  <br />
  <hr />
  {% endfor %}
</div>
{% endblock %}

templates/show_my_market.html
{% extends "base\base.html" %}
{% load static %}

{% block content %}
    <h1 align="center">Продукты с подходящим сроком годности</h1>
    <div align="center">
        <h4> Сегодня: {{ date|date:"l d M Y" }}</h4>
        <br><HR>
        <form method="POST">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Выбрать магазин">
        </form>
        <br><HR>
        <ul>
            <li><a class="" href="{% url 'market_dashbord:show_all_markets' %}">Список Магазинов</a></li>
        </ul>
            

    </div>
{% endblock content %}

templates/show_write_off.html
{% extends "base\base.html" %} {% load static %} {% block content %}
<h1 align="center">Продукты с подходящим сроком годности</h1>
<div align="center">
  <h4>Сегодня: {{ date|date:"l d M Y" }}</h4>
  <br />
  <hr />
  <br />
  {% for product in all_items %}
  <div
    class="card rounded border border-1 border-primary"
    style="max-width: 35rem"
  >
    <img src="{{ product.img.url }}" class="card-img-top" alt="..." />
    <div class="card-body">
      <h5 class="card-title">Название: {{ product.product_name }}</h5>
      <!-- <p class="card-text">Небольшой пример текста, который должен основываться на названии карты и составлять основную часть содержимого карты.</p> -->
    </div>
    <ul class="list-group list-group-flush">
      <li class="list-group-item">Годен до: {{ product.date_best_before }}</li>
      {% if product.is_expired %}
      <li class="list-group-item">Просрочен</li>
      {% endif %}
      {% if product.write_off %}
      <li class="list-group-item">Списан</li>
      {% endif %}

      <li class="list-group-item">ШК: {{ product.barcode }}</li>
      <li class="list-group-item">{{ product.number_of_market }}</li>
    </ul>

  </div>

  <br />
  <hr />
  <br />

  {% endfor %}
</div>
{% endblock content %}